server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions_automation-devops.yaml

clients:
  - url: http://100.64.0.10:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    pipeline_stages:
      - docker: {}
    static_configs:
      - targets: ["localhost"]
        labels:
          job: docker
          node: "automation-devops"
          __path__: /var/lib/docker/containers/*/*.log
