http:
  middlewares:
    authentik-forwardauth:
      forwardAuth:
        address: "http://ak-outpost-traefik:9000/akprox/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - "Set-Cookie"
          - "Authentication-Info"

  routers:
    traefik-dashboard:
      rule: "Host(`traefik.${DOMAIN}`)"
      service: api@internal
      entryPoints:
        - websecure
      tls: true
      middlewares:
        - authentik-forwardauth
